---
name: "Home Assistant Community Apps Repository Updater"
description: Tool for updating Home Assistant Apps repositories.
author: frenck

branding:
  color: red
  icon: thumbs-up

inputs:
  token:
    description: GitHub token that is allowed to write/commit to the target repo
    required: true
  repository:
    description: The app repository to update (e.g., frenck/repository)
    required: false
  app:
    description: Slug of the app to update the repository for
    required: false
  addon:
    description: (Deprecated) Use 'app' instead. Slug of the app to update the repository for
    required: false
  email:
    description: Email address used to write/commit to the target repo, required when the token is associated with a user that does not have a public email address
    required: false
  force:
    description: Force repository update, even if no changes are detected
    default: "false"
    required: false

runs:
  using: "docker"
  image: "action/Dockerfile"
